version: "3"


services:
  web:
    restart: always
    volumes:
      - ./project:/project
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
