version: "3"


services:
  web:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nginx:
    restart: always
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes: 
      - ./project/static/:/static
      - ./project/media/:/media
    depends_on: 
      - web
    ports: 
      - "80:80"