# Generated by Django 3.2.8 on 2021-11-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20211008_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myyoutube',
            old_name='abs_path',
            new_name='absolute_path',
        ),
        migrations.RenameField(
            model_name='myyoutube',
            old_name='sl_title',
            new_name='slug_title',
        ),
    ]
