# Generated by Django 3.2.8 on 2021-11-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20211101_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myyoutube',
            options={'ordering': ('-created',), 'verbose_name': 'Youtube object', 'verbose_name_plural': 'Youtube objects'},
        ),
    ]
