# Generated by Django 3.2.8 on 2022-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_myyoutube_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(blank=True, max_length=255)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ('-visit_time',),
            },
        ),
        migrations.AddField(
            model_name='myyoutube',
            name='user_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
